title: What is Nuclear?
email: contact@whatisnuclear.com
description: >-
  A no-nonsense public education site on nuclear energy.
baseurl: ""
url: "https://whatisnuclear.com"
twitter_username: whatisnuclear
github_username: whatisnuclear
github_repo_url: https://github.com/whatisnuclear/website/blob/master/
title_image: https://whatisnuclear.com/img/reactor_200.png
future: true
markdown: kramdown
highlighter: rouge
collections:
  # posts collection is hard-coded into jekyll
  posts:
    output: true
    permalink: /news/:year-:month-:day-:title.html
    future: true
  safetyminutes:
    output: true
    directory: safetyminutes
    permalink: /safety-minutes/:title.html
  calcs:
    output: true
    directory: calcs
    permalink: /calcs/:title.html

kramdown:
  toc_levels: "1,2,3"

plugins:
  - jekyll-sitemap
  - jekyll-time-to-read
  - jekyll-feed
  - jekyll-image-size
  - jekyll-exif-data
  - "jekyll/scholar"

feed:
  collections:
    posts:
      # This is the main news section describing changes and additions to the site.
      # This is what people would likely point their feed reader too
      path: "/feed.xml"
  # for speed
  

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - README.md
  - .git
  - .jekyll-cache
  - .vscode

scholar:
  source: assets/
  # for now refs.bib has to be manually copied from /pool/Reading when updated.
  bibliography: refs.bib
  bibtex_filters:
    - latex
    # trying to get html hyperlinks from urls in refs.... doesn't work. just
    # prints out [markdown](woo)
    # https://github.com/inukshuk/jekyll-scholar/issues/30
    #- markdown

defaults:
  - scope:
      path: ""
    values:
      reading_time: true
