name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  prettier:
    runs-on: docker
    container: node:20-bookworm
    steps:
      - uses: actions/checkout@v4

      - uses: actions/cache@v4
        with:
          path: ~/.npm
          key: npm-${{ hashFiles('package-lock.json') }}
          restore-keys: npm-

      - run: npm ci

      - name: Check formatting with Prettier
        run: npx prettier --check .

  build-and-validate:
    runs-on: win-ci
    steps:
      - uses: actions/checkout@v4

      - name: Build site
        run: bundle exec jekyll build

      - name: Validate HTML
        run: >
          java -jar /usr/local/lib/vnu.jar
          --no-stream
          --format text
          --filterpattern
          ".*Trailing.*|.*:key.*|.*@click.*|.*:label.*|.*v-if.*|.*v-else.*|.*v-for.*|.*:color.*"
          _site/*.html
